version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}